### PR TITLE
add cache

### PR DESCRIPTION
**Pull request by xyuanlu**
### Description

This pull request introduces a caching mechanism for the Helix Gateway service. The main changes include:

1. Addition of a new `GatewayCurrentStateCache` class in `GatewayCurrentStateCache.java`, which manages caching of current and target states for instances in a cluster.

2. Modification of `GatewayServiceManager.java` to incorporate the new caching functionality:
   - A new `_currentStateCacheMap` is added to store `GatewayCurrentStateCache` objects for each cluster.
   - A new method `getCurrentStateCache(String clusterName)` is introduced to retrieve or create a cache for a given cluster.

3. Implementation of various methods in `GatewayCurrentStateCache` to handle cache updates, state changes, and serialization of target assignments.

These changes aim to improve performance and efficiency by reducing the need for frequent state lookups and updates.

### Test

A new test class `TestGatewayCurrentStateCache.java` has been added with the following tests:

1. `testUpdateCacheWithNewCurrentStateAndGetDiff()`: Verifies the correct updating of the cache with new current states and retrieval of differences.
2. `testUpdateCacheWithCurrentStateDiff()`: Checks the updating of the cache with current state differences.
3. `testUpdateTargetStateWithDiff()`: Ensures proper updating of target states and change detection.
4. `testSerializeTargetAssignments()`: Validates the serialization of target assignments.

These tests cover the core functionality of the new `GatewayCurrentStateCache` class.

### Changes that Break Backward Compatibility

N/A

### Documentation

N/A

*Created with [Palmier](https://www.palmier.io)*

### CODE REVIEW

**Comment by htin1** [comment]
@palmier-bot describe

**Comment by xyuanlu** [comment]
@palmier-bot review

**Comment by xyuanlu** [comment]
@palmier-bot review

**Comment by htin1** [comment]
@palmier-bot review

**Comment by htin1** [comment]
> @palmier-bot review

hi @xyuanlu , sorry for the bug :( I see the logs saying "No Suggestions found" and we didn't print anything in that case. I will update the bot!

**Pull request closed without merging**
